
// request for https://marketplace.visualstudio.com/items?itemName=humao.rest-client 


POST http://localhost:3000/api/subscribe HTTP/1.1
content-type: application/json

{
    "username": "userA"
}
###

POST http://localhost:3000/api/login HTTP/1.1
content-type: application/json

{
    "username": "userA"
}

### user list

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "username": "userA"
}